#ifdef __YUNI_SCRIPT_SCRIPT_DEFINES_H__

# undef YUNI_SCRIPT_SCRIPT_ANY
# undef YUNI_SCRIPT_SCRIPT_1_ANY
# undef YUNI_SCRIPT_SCRIPT_2_ANYS
# undef YUNI_SCRIPT_SCRIPT_3_ANYS
# undef YUNI_SCRIPT_SCRIPT_4_ANYS
# undef YUNI_SCRIPT_SCRIPT_5_ANYS
# undef YUNI_SCRIPT_SCRIPT_6_ANYS
# undef YUNI_SCRIPT_SCRIPT_7_ANYS
# undef YUNI_SCRIPT_SCRIPT_8_ANYS
# undef YUNI_SCRIPT_SCRIPT_DECLARE_CALL_WITH

# undef __YUNI_SCRIPT_SCRIPT_DEFINES_H__
#endif /* __YUNI_SCRIPT_SCRIPT_DEFINES_H__ */
