#include "../logs/logs.h"
#include "paths.h"
#include "files.h"
#include "tdf.h"
#include "modinfo.h"

namespace TA3D
{
    ModInfo::ModInfo(const int ID, const String &name, const String &version, const String &author, const String &comment, const String &url)
        : ID(ID), name(name), version(version), author(author), comment(comment), url(url)
    {
    }

    ModInfo::ModInfo(const String &info)
    {
        parse(info);
    }

    void ModInfo::parse(const String &info)
    {
        String::Vector params;

        String::Size pos = 0;
        while((pos = info.find_first_of("\"", pos)) != String::npos)
        {
            ++pos;
            String p;
            while(pos < info.size() && info[pos] != '"')
            {
                if (info[pos] == '\\' && pos + 1 < info.size())
                {
                    ++pos;
                    p << info[pos];
                }
                else
                    p << info[pos];
                ++pos;
            }
            ++pos;
            params.push_back(p);
        }

        if (params.size() != 6)     // If there is not the expected number of parameters, then we can't trust this information
        {
            *this = ModInfo();
            return;
        }

        ID = params[0].to<sint32>();
        version = params[1];
        name = params[2];
        url = params[3];
        author = params[4];
        comment = params[5];
    }

    void ModInfo::read(const String &modName)
    {
        String filename = Paths::Resources;
        filename << "mods" << Paths::Separator << modName << Paths::Separator << "info.mod";

        TDFParser file(filename, false, true, false, true);
        ID = file.pullAsInt("mod.ID", -1);
        name = file.pullAsString("mod.name");
        version = file.pullAsString("mod.version");
        author = file.pullAsString("mod.author");
        comment = file.pullAsString("mod.comment");
        url = file.pullAsString("mod.url");
    }

    void ModInfo::write()
    {
        if (name.empty())       // Don't save empty data
            return;

        String filename = Paths::Resources;
        filename << "mods" << Paths::Separator << name << Paths::Separator << "info.mod";

        String file;
        file << "// TA3D Mod info file\n"
        << "// autogenerated by ta3d\n"
        << "[mod]\n"
        << "{\n"
        << "    ID = " << ID << ";\n"
        << "    name = " << name << ";\n"
        << "    version = " << version << ";\n"
        << "    author = " << author << ";\n"
        << "    comment = " << comment << ";\n"
        << "    url = " << url << ";\n"
        << "}";
        Paths::Files::SaveToFile(filename, file);
    }
}
