/*  TA3D, a remake of Total Annihilation
    Copyright (C) 2006  Roland BROCHARD

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA*/

/*
**  File: stdafx.h
** Notes:  **** PLEASE SEE README.txt FOR LICENCE AGREEMENT ****
**  Cire: *stdafx.h and stdafx.cpp will generate a pch file
**         (pre compiled headers).
**        *All other cpp files MUST include this file as its first include.
**        *No .h files should include this file.
**        *The goal is to include everything that we need from system, and
**          game libiries, ie everything we need external to our project.
*/

#ifndef __TA3D_STDAFX_H__
# define __TA3D_STDAFX_H__

// Include the config options generated by the configure script
# include "../config.h"

# ifdef TA3D_PLATFORM_WINDOWS
#   ifndef _MSC_VER
#       define TA3D_PLATFORM_GCC
#       define TA3D_PLATFORM_MINGW
#   else
#       define TA3D_PLATFORM_MSVC
#   endif
# endif



# ifndef TA3D_PLATFORM_MSVC
#    include <stdint.h>
# endif

# if defined TA3D_PLATFORM_WINDOWS && defined TA3D_PLATFORM_MSVC
#   if defined (_INTEGRAL_MAX_BITS) && _INTEGRAL_MAX_BITS >= 64 // For Visual 6.x and later
    // 64-bit ints, guaranteed to be 4 bytes in size
	typedef unsigned __int64  uint64;
	typedef signed __int64    sint64;
#   else
#       error __int64 type not supported
#   endif
	// 32-bit ints, guaranteed to be 4 bytes in size
	typedef unsigned __int32  uint32;
	typedef signed __int32    sint32;
	// 16-bit ints, guaranteed to be 2 bytes in size
	typedef unsigned __int16  uint16;
	typedef signed __int16    sint16;
	// 8-bit ints, guaranteed to be 1 byte in size
	typedef unsigned __int8   uint8;
	typedef signed __int8     sint8;
# else
    // 64-bit ints, guaranteed to be 8 bytes in size
	typedef uint64_t  uint64;
	typedef int64_t   sint64;
	// 32-bit ints, guaranteed to be 4 bytes in size
	typedef uint32_t  uint32;
	typedef int32_t   sint32;
	// 16-bit ints, guaranteed to be 2 bytes in size
	typedef uint16_t uint16;
	typedef int16_t  sint16;
	// 8-bit ints, guaranteed to be 1 byte in size
	typedef uint8_t uint8;
	typedef int8_t  sint8;
# endif




/*
** The SDL library
*/
# if defined TA3D_PLATFORM_WINDOWS //&& defined TA3D_PLATFORM_MSVC
#   include <windows.h>
#   ifdef TA3D_PLATFORM_MSVC
#      pragma warning(disable : 4554)
#      pragma warning(disable : 4996)
#      pragma comment( lib, "opengl32.lib" )
#      pragma comment( lib, "glu32.lib" )
#      pragma comment( lib, "glaux.lib" )
#      pragma comment( lib, "tools/win32/msvc/libs/glew32.lib" )
#      include "tools/win32/include/GL/glew.h"
    // Cire: I had to setup a pragma on c4312, 4005 warnings, because allgero include
    //  was generating alot of compiler noise.
#      pragma warning( disable : 4312 )
#      pragma warning( disable : 4005 )
#   endif
#   include "tools/win32/mingw32/include/GL/glew.h"
#   include "SDL.h"
#   include "SDL_image.h"
    // Cire: Restore warning states
#   ifdef TA3D_PLATFORM_MSVC
#      pragma warning( default : 4005 )
#      pragma warning( default : 4312 )
#   endif
# else
/*
** The OpenGL library
*/
#   include <GL/glew.h>
#   include "SDL.h"
#   include "SDL_image.h"
#endif

# include "misc/string.h"


// Cire:
//   Since byte seems to be common throughout the project we'll typedef here.
typedef uint8         byte;
typedef unsigned char uchar;
typedef signed char   schar;

// Floating point types, defined for consistencies sakes.
typedef float  real32;
typedef double real64;



#if defined TA3D_PLATFORM_WINDOWS && defined TA3D_PLATFORM_MSVC
	#define strcasecmp(x,xx) _stricmp( x, xx )
#endif


/*!
** \brief Delete a variable if != NULL then sets it to NULL
*/
# define DELETEANDNIL(X) do { if (X) { delete X; X = NULL; } } while(0)




/*!
** \brief The hard limit for the number of players
*/
# define TA3D_PLAYERS_HARD_LIMIT   10


#define TA3D_API_SI static inline
#define TA3D_API_EI extern inline
#define TA3D_API_S static
#define TA3D_API_E extern


namespace TA3D
{

    //! \name String manipulations
    //@{

    String format(const char* fmt, ...);

    sint32 SearchString(const String& s, const String& StringToSearch, const bool ignoreCase);

    String ReplaceString(const String& s, const String& toSearch, const String& replaceWith, const bool ignoreCase);

    String ReplaceChar(const String& s, const char toSearch, const char replaceWith);

    bool StartsWith(const String& a, const String& b);

    //@} String manipulations

    #if defined TA3D_PLATFORM_WINDOWS && defined TA3D_PLATFORM_MSVC
	void ExtractPathFile(const String& szFullFileName, String& szFile, String& szDir);
    #endif


	String GetClientPath(void);

    uint32 file_size(const String &filename);

    int ASCIItoUTF8(const byte c, byte *out);

    String InttoUTF8(const uint16 c);

    wchar_t *UTF8toWChar_t(const String &str);

    bool exists(const String &filename);

    void rest(uint32 msec);
} // namespace TA3D

#define FILE_SIZE	file_size

#ifdef TA3D_PLATFORM_WINDOWS
# define FA_FILE     1
# define FA_DIREC    2
#else
# define FA_FILE     DT_REG
# define FA_DIREC    DT_DIR
#endif

#define FA_ALL      (FA_FILE | FA_DIREC)

// zuzuf: to prevent some warnings
# undef PACKAGE_BUGREPORT
# undef PACKAGE_NAME
# undef PACKAGE_TARNAME
# undef PACKAGE_STRING
# undef PACKAGE_VERSION


#endif // __TA3D_STDAFX_H__
